version: "3.9"

services:
  app:
    container_name: ifc_backend
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads  # ✅ CORRETO
    environment:
      - DATABASE_URL=postgresql://ifc_user:iE6B8eA6QjBP6BIPV3awhE2CKbLsfIAi@dpg-d783dp5m5p6s73ehplk0-a/ifc_db_kvkz
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"

  db:
    image: postgres:15-alpine
    container_name: ifc_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ifc_user
      - POSTGRES_PASSWORD=iE6B8eA6QjBP6BIPV3awhE2CKbLsfIAi
      - POSTGRES_DB=ifc_db_kvkz
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: